### ISSUE TITLE
As a PO(Aurilla), I would like to see the Risk management, so that I can assess the project

### ISSUE THREAD

**Issue by Bozhao-Liu** [Artibot/Autonomous-Car-CHEBB#5]

**Comment by bilgehanG** [comment]
Computer crashing [p]: 1, S: 5, Impact: 5, (Description: Likelihood of any computer we use crashing)

**Comment by Bozhao-Liu** [comment]
Risk: No environment to perform the testing
Probability: 3
Severity: 5
Impact: Unreliable product; delay of deployment;

**Comment by ChrisanderB** [comment]
Risk: Data Loss
Description: If the project documents gets deleted or corrupted.
Probability: 1
Severity: 5
Impact: 5
Prentive Action: Backup of all documentation in either Google Drive, Local hard drive, etc
Action to take: All documentation must be rewritten ASAP.

**Comment by bilgehanG** [comment]
impact = p * s

**Comment by HusoD** [comment]
Risk: A member quitting the team
Probability: 1
Severity: 4
Impact: 4
Make sure that another team member can be able to continue with his work

**Comment by EndHa** [comment]
Risk: Absence of member in daily meeting
Mitigation: Make sure everyone knows when the meeting is.
Probability: 4
Severity: 2
Impact: 3
Preventive action: Give extra work for absent member.

**Comment by bilgehanG** [comment]
Risk: Lack of knowledge
Probability: 3
Severity: 4
Impact: 12
Description: If we do not have enough knowledge to continue with our project work.
To prevent: Make a plan on which materials we need to learn beforehand.
Action to take: Ask other students/teachers and start learning the unsufficient knowledge from the internet.

**Comment by Bozhao-Liu** [comment]
Risk: the car doesn't match the global standard.
Probability: 
Severity:
Impact:
Discription
